const PAPEL_USUARIO = ["ADMIN", "ALUNO", "PROFESSOR", "FUNCIONARIO"];
const STATUS_USUARIO = ["PENDENTE", "APROVADO", "BLOQUEADO", "REJEITADO"];
const STATUS_SOLICITACAO = ["PENDENTE", "APROVADO", "REJEITADO"];
const STATUS_SALA = ["ATIVA", "SILENCIADA", "EXCLUIDA"];
const TIPO_MENSAGEM = ["TEXTO", "CODIGO", "EVENTO_SISTEMA", "AVISO_MODERACAO"];
const TIPO_EVENTO_PARTICIPACAO = ["ENTRADA", "SAIDA"];
const TIPO_ACAO_MODERACAO = [
  "APROVAR_USUARIO",
  "REJEITAR_USUARIO",
  "BLOQUEAR_USUARIO",
  "EXCLUIR_MENSAGEM",
  "SILENCIAR_SALA",
  "EXCLUIR_SALA",
  "ENVIAR_AVISO_MODERACAO",
];

module.exports = {
  PAPEL_USUARIO,
  STATUS_USUARIO,
  STATUS_SOLICITACAO,
  STATUS_SALA,
  TIPO_MENSAGEM,
  TIPO_EVENTO_PARTICIPACAO,
  TIPO_ACAO_MODERACAO,
};
